### ISSUE TITLE
没有后续了

### ISSUE THREAD

**Issue by tangyumeng** [imfycc/beijing-house#1]
没有继续更新内容

**Comment by imfycc** [comment]
亲，您的邮件我收到了，感谢您的来信。

**Comment by tangyumeng** [comment]
> > 没有继续更新内容
> 
> 你想了解什么呀？我可以继续补充，有支持就有动力嘛。

比如是否已经买完房了？买房过程中自己的考虑重点（怎样确定在哪个区买、预算范围内怎样选等）。
看房过程中有比较好的经验供其他人参考一下等。
